package com.revature.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "userinfo")
public class Userinfo {
	
	@Id //denotes that this column is the primary key for this table.
	@Column
	String username;
	
	@Column
	String pass; 
	
	@Column
	int age;
	
	@Column
	int height;
	
	@Column
	int weight;
	
	
	@Column
	@GeneratedValue(generator = "user_id_seq", strategy = GenerationType.AUTO) //specifies that this ID is auto generated by some sort of sequence
	@SequenceGenerator(name="user_id_seq", allocationSize = 1) //Generates the sequence you want to use
	int userID;
	
	public Userinfo() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Userinfo(String username, String pass, int age, int height, int weight, int userID) {
		super();
		this.username = username;
		this.pass = pass;
		this.age = age;
		this.height = height;
		this.weight = weight;
		this.userID = userID;
	}

	@Override
	public String toString() {
		return "Userinfo [username=" + username + ", pass=" + pass + ", age=" + age + ", height=" + height + ", weight="
				+ weight + ", userID=" + userID + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + age;
		result = prime * result + height;
		result = prime * result + ((pass == null) ? 0 : pass.hashCode());
		result = prime * result + userID;
		result = prime * result + ((username == null) ? 0 : username.hashCode());
		result = prime * result + weight;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Userinfo other = (Userinfo) obj;
		if (age != other.age)
			return false;
		if (height != other.height)
			return false;
		if (pass == null) {
			if (other.pass != null)
				return false;
		} else if (!pass.equals(other.pass))
			return false;
		if (userID != other.userID)
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		if (weight != other.weight)
			return false;
		return true;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPass() {
		return pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getHeight() {
		return height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public int getWeight() {
		return weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public int getUserID() {
		return userID;
	}

	public void setUserID(int userID) {
		this.userID = userID;
	}

	

	
	
}